### ISSUE TITLE
Decidir o nome da aplicação

### ISSUE THREAD

**Issue by KatsutoshiRF** [KatsutoshiRF/N.E.R.D-project#11]

**Comment by vitorguimars** [comment]
Sugestão do nome do App : "GeekForc"

**Comment by RicardoCA** [comment]
Sugestão do nome: "Nerd Executioner"

**Comment by kstkelvin** [comment]
Sugestões de nomes para o App:
1- "HanGeek"
2- "Reino dos Tentáculos" (kkkkk')

**Comment by masmangan** [comment]
Nerd Tie

**Comment by brunoribs** [comment]
Não Enforque o Nerd

**Comment by KatsutoshiRF** [comment]
The Nerd Master

**Comment by PedroSchwarz** [comment]
Nerdom (Tipo reinado do nerd, sei lá)

**Comment by Ravelliserpa** [comment]
MAXIMUS Nerd Hangman

**Comment by KatsutoshiRF** [comment]
Nome decidido por votação
HanGeek - 4
Nerd Master - 3
Nerd Executioner - 1
